options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2

  # Mixins
  mixins-before-declarations: 2

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks:
        - 2
        -
          allow-single-line-rulesets: false

  single-line-per-selector: 2

  # Disallows
  no-color-keywords: 2
  no-color-literals:
        - 1
        -
          allow-rgba: true

  no-css-comments: 2
  no-debug: 2
  no-duplicate-properties:
    - 1
    -
      exclude: ["display","width","height"]

  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 0
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements: 1
  no-trailing-zero: 2
  no-transition-all: 0
  no-url-protocols: 1
  no-vendor-prefixes: 2
  no-warn: 2
  property-units:
      - 1
      -
        global: ["px","rem"]
        per-property: { font-size: ["rem"] }

  # Nesting
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format:
      - 1
      -
        ignore: ["dataTable","sorting_asc","sorting_desc","sorting_asc_disabled","sorting_desc_disabled"]

  function-name-format: 1
  id-name-format: 1
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format: 1

  # Style Guide
  bem-depth: 0
  border-zero: 2
  brace-style:
      - 2
      -
        allow-single-line: false

  clean-import-paths: 0
  empty-args: 2
  hex-length: 2
  hex-notation: 2
  indentation:
      - 2
      -
        size: 4

  leading-zero: 2
  nesting-depth:
      - 1
      -
        max-depth: 4

  property-sort-order:
      - 1
      -
        order: "recess"

  quotes:
      - 1
      -
        style: double

  shorthand-values: 1
  url-quotes: 2
  variable-for-property:
      - 2
      -
        properties: ["content","font-family"]

  zero-unit: 2

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 2
  space-around-operator: 2

  # Final Items
  trailing-semicolon: 2
  final-newline: 0